In [1]:
import numpy as np

In [2]:
Fnp = np.array([1,2,3,4])

In [3]:
print(Fnp)

[1 2 3 4]


In [5]:
zero_np = np.zeros((3,3))
print(zero_np)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
ones_np = np.ones((3,3))
print(ones_np)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
empty_np = np.empty((2,3))
print(empty_np)

[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
arange_np = np.arange(12)
print(arange_np)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [15]:
#reshape
arange_np.reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
linspace_np = np.linspace(0,1,5)
print(linspace_np)

[0.   0.25 0.5  0.75 1.  ]


In [23]:
# Numpy shapes and Axes 

In [24]:
np.array(24)

array(24)

In [25]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [42]:
array_np1 = np.array([[1,1,1],[2,2,1]])

In [44]:
array_np1.shape

(2, 3)

In [32]:
np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])

TypeError: Field elements must be 2- or 3-tuples, got '[3, 3, 3]'

In [40]:
array_np2 = np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])

In [41]:
array_np2.shape

(2, 2, 3)

In [45]:
array_np2.ndim

3

In [46]:
one_np = np.array([x for x in range(1,10)])

In [47]:
one_np

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
# converting the above one-D array to 2D array

In [50]:
one_np.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
numpy_arr = np.array([x for x in range(1,13)])

In [60]:
numpy_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [61]:
numpy_arr.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [62]:
numpy_arr.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [63]:
numpy_arr.reshape(3,3,2)

ValueError: cannot reshape array of size 12 into shape (3,3,2)

In [65]:
numpy_arr.reshape(2,2,-1)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [72]:
A = np.array([[1,2,1],[2,2,3]])
B = np.array([3,4,5])

In [74]:
A.shape

(2, 3)

In [75]:
B.shape

(3,)

In [76]:
np.add(A,B)

array([[4, 6, 6],
       [5, 6, 8]])

In [78]:
np.subtract(B,A)

array([[2, 2, 4],
       [1, 2, 2]])

In [79]:
np.multiply(A,B)

array([[ 3,  8,  5],
       [ 6,  8, 15]])

In [80]:
np.divide(A,B)

array([[0.33333333, 0.5       , 0.2       ],
       [0.66666667, 0.5       , 0.6       ]])

In [82]:
np.power(A,2)

array([[1, 4, 1],
       [4, 4, 9]], dtype=int32)

In [83]:
np.power(A,B)

array([[  1,  16,   1],
       [  8,  16, 243]])

In [85]:
x = np.array([i for i in range(10)])

In [86]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
np.where(x%2==0,'Even','Odd')

array(['Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd'], dtype='<U4')

In [91]:
condlist = [x<5,x>5]
choicelist = [x**2,x**3]

In [92]:
np.select(condlist,choicelist,default=x)

array([  0,   1,   4,   9,  16,   5, 216, 343, 512, 729])

In [93]:
arr = np.array([[4,3,2],[10,1,0],[5,8,24]])

In [94]:
arr

array([[ 4,  3,  2],
       [10,  1,  0],
       [ 5,  8, 24]])

In [97]:
np.amin(arr)

0

In [99]:
np.amin(arr, axis = 0)

array([4, 1, 0])

In [101]:
np.amin(arr, axis = 1)

array([2, 0, 5])

In [98]:
np.amax(arr)

24

In [100]:
np.amax(arr, axis = 0)

array([10,  8, 24])

In [102]:
np.amax(arr, axis = 1)

array([ 4, 10, 24])

In [103]:
np.median(arr)

4.0

In [104]:
np.mean(arr)

6.333333333333333

In [105]:
np.std(arr)

6.944222218666553

In [106]:
np.var(arr)

48.22222222222222

In [108]:
np.percentile(arr,50)

4.0

In [109]:
deg = np.array([0,30,45,60,90])

In [110]:
np.sin(deg*np.pi/180)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [111]:
np.cos(deg*np.pi/180)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [112]:
np.tan(deg*np.pi/180)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])